Added TypeScript type definitions
CorsairOfficial/cue-sdk-node pull request #13
Opened 2021-03-25 06:57 UTC by WhySoBad

I added an index.d.ts file.
This allows to get intellisense support for regular usage with JavaScript and to use this library with TypeScript using the type definitions.

2021-04-23 21:39 UTC, intrueder requested changes

2021-04-23 21:39 UTC, intrueder commented on index.d.ts
> +    channelsCount: number
This does not look complete

2021-04-23 21:39 UTC, intrueder commented on index.d.ts
> +export interface CorsairDevice {
Should be named `CorsairDeviceInfo`

2021-04-23 21:39 UTC, intrueder commented on index.d.ts
> +export function CorsairRequestControl(): void
Returns `boolean`, see https://corsairofficial.github.io/cue-sdk/#corsairrequestcontrol

2021-04-23 21:39 UTC, intrueder commented on index.d.ts
> +export function CorsairReleaseControl(): void
Returns `boolean`

2021-04-23 21:39 UTC, intrueder commented on index.d.ts
> + * Function to unsubscribe to events
to events -> from events

2021-04-24 14:22 UTC, WhySoBad commented on index.d.ts
> +    channelsCount: number
In the [CUE SDK documentation](https://corsairofficial.github.io/cue-sdk/#corsairdeviceinfo) is a property deviceId for the CorsairDeviceInfo but I didn't manage to get this with any of my devices. Does this property really exist?

2021-04-25 06:13 UTC, intrueder commented on index.d.ts
> +    channelsCount: number
I'll create an issue for this, js wrapper does not have CorsairDeviceInfo.deviceId property but it does exist in the CUESDK.

2021-04-25 06:18 UTC, intrueder commented on index.d.ts
> +    channelsCount: number
#15 will fix it once this PR is merged

2021-04-25 06:29 UTC, intrueder approved these changes
LGTM

2021-04-25 06:31 UTC, merged